data_dir: /home/avishka/biyon/data
clip_model_dir: ../clip_model
save_model_dir: /home/avishka/biyon/MV/Assignment/saved_models

clip_model_parameters:
  ViT_model: ViT-B/32 
  embedding_size: 512

embedding_size: 512 

output_size: 37

num_epochs: 7

batch_size: 32

lr0: 0.01
lr: 0.000001

weight_decay: 0.0001

validation_split: 0.2

random_seed: 42