save_train_test_embeddings: False
save_embeddings_dir: /home/avishka/biyon/MV/Assignment/embeddings

data_dir: /home/avishka/biyon/data
clip_model_dir: ../clip_model

clip_model_parameters:
  ViT_model: ViT-B/32
  embedding_size: 512

knn_parameters:
  num_neighbours_min: 5
  num_neighbours_max: 300
  num_neighbours_interval: 10
  algorithm: auto